[build]
  publish = "."
  command = "echo 'Static site - no build required'"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[dev]
  port = 8888
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"